export const enum CssClass {
  SELECTING = "a",
  DISABLED = "disabled",
  HIDDEN = "hidden",
  SCARED = "d",
  SCARY = "e",
  T13A = "f",
  P_T13A = "g",
  HAS_CAT = "h",
  HAS_LEFT = "i",
  HAS_RIGHT = "j",
  CELL = "cell",
  ONBOARDING_HIGHLIGHT = "onboarding-highlight",
  ANIMATED = "animated",

  // arrows
  UP = "up",
  DOWN = "down",
  LEFT = "left",
  RIGHT = "right",
  ARROW = "arrow",

  // controls
  CONTROLS = "controls",
  MOVEMENT_CONTROLS = "movement-controls",
  MOVES = "moves",
  TOOL_CONTROLS = "tool-controls",
  MEOW_BUTTON = "meow",
  CONFIG = "config",
  CONFIG_CATEGORY = "category",
  SELECTED = "selected",

  TABLE = "z",
  IS_MOM = "is-mom",
  CAT = "cat",
  CAT_BOX = "cat-box",
  CAT_COLOR = "cat-color",
  TREE = "tree",
  PUDDLE = "puddle",
  MOON = "moon",
  EMOJI = "emoji",
  FIELD = "field",
  WON = "won",
  START_BUTTON = "start-button",
  NEW_GAME_CONTAINER = "new-game",
}
