export const enum CssClass {
  SELECTING = "a",
  SELECTED = "b",
  PANIC = "c",
  SCARED = "d",
  SCARY = "e",
  T13A = "f",
  P_T13A = "g",
  HAS_CAT = "h",
  HAS_LEFT = "i",
  HAS_RIGHT = "j",
  CELL = "cell",
  IS_DRAGGING = "l",
  ANIMATED = "animated",

  // arrows
  UP = "up",
  DOWN = "down",
  LEFT = "left",
  RIGHT = "right",
  ARROW = "arrow",

  // controls
  CONTROLS = "controls",
  MOVEMENT_CONTROLS = "movement-controls",
  ACTION_CONTROLS = "u",
  STATS_GRID = "v",
  STAT = "w",
  GOOD = "x",
  BAD = "y",

  TABLE = "z",
  MIDDLE = "A",
  IS_MOM = "is-mom",
  CAT = "cat",
  CAT_SIZE = "cat-size",
  EMOJI = "emoji",
  FIELD = "field",
  WON = "won",
  START_BUTTON = "start-button",
}
